### ISSUE TITLE
Heroku, problems

### ISSUE THREAD

**Issue by mcm2007** [alfio-event/alf.io#1027]
Hey! So, when i try to deploy the app into heroku using this steps (https://alf.io/docs/getting-started/deployment/heroku/) this happends: Uploading alfio-2.0-M3-2107-boot.war
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs: [
    '-Dheroku.appName=cinemamigams',
    '-Xmx1g',
    '-Dheroku.jdkVersion=11',
    '-Dheroku.jarFile=alfio-2.0-M3-2107-boot.war',
    '-Dheroku.jarOpts=',
    '-cp',
    'C:\\Users\\User\\AppData\\Local\\heroku\\node_modules\\@heroku-cli\\plugin-java\\lib\\heroku-deploy-complete.jar',
    'com.heroku.sdk.deploy.DeployJar'
  ]
}

**Comment by almightybob** [comment]
I have the same issue
