### ISSUE TITLE
SMTP doesn't work

### ISSUE THREAD

**Issue by AdriDevelopsThings** [alfio-event/alf.io#1048]
**Describe the bug**
I configured SMTP (mailcow server) with STARTTLS and the emails are not sent.

**To Reproduce**
- Use a mailcow server
Use the following configuration paramenters:
- hostname: mail.example.org
- port: 587
- smtp protocol: smtp
- smtp username: noreply@example.org
- smtp password: ur password
- e-mail sender: noreply@example.org
- smtp properties: mail.smtp.starttls.enable=true

**Expected behavior**
The E-Mail would be sent.

**Behavior**
I get the following error:
```
alfio_1  | 22:26:20.052 [scheduling-1] WARN  alfio.manager.NotificationManager - could not send message: 
alfio_1  | org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not connect to SMTP host: mail.adridoesthings.com, port: 587;
alfio_1  |   nested exception is:
alfio_1  |      java.net.ConnectException: Operation timed out (Connection timed out). Failed messages: javax.mail.MessagingException: Could not connect to SMTP host: mail.adridoesthings.com, port: 587;
alfio_1  |   nested exception is:
alfio_1  |      java.net.ConnectException: Operation timed out (Connection timed out)
alfio_1  |      at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:448) ~[spring-context-support-5.2.5.RELEASE.jar:5.2.5.RELEASE]
alfio_1  |      at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:361) ~[spring-context-support-5.2.5.RELEASE.jar:5.2.5.RELEASE]
alfio_1  |      at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:378) ~[spring-context-support-5.2.5.RELEASE.jar:5.2.5.RELEASE]
alfio_1  |      at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:366) ~[spring-context-support-5.2.5.RELEASE.jar:5.2.5.RELEASE]
alfio_1  |      at alfio.manager.system.SmtpMailer.send(SmtpMailer.java:88) ~[classes/:?]
alfio_1  |      at alfio.manager.system.DefaultMailer.send(DefaultMailer.java:60) ~[classes/:?]
alfio_1  |      at alfio.manager.NotificationManager.sendMessage(NotificationManager.java:349) ~[classes/:?]
alfio_1  |      at alfio.manager.NotificationManager.lambda$processMessage$19(NotificationManager.java:334) ~[classes/:?]
alfio_1  |      at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.5.RELEASE.jar:5.2.5.RELEASE]
alfio_1  |      at alfio.manager.NotificationManager.processMessage(NotificationManager.java:333) ~[classes/:?]
alfio_1  |      at alfio.manager.NotificationManager.lambda$sendWaitingMessages$16(NotificationManager.java:316) ~[classes/:?]
alfio_1  |      at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
alfio_1  |      at java.util.stream.DistinctOps$1$2.accept(Unknown Source) ~[?:?]
alfio_1  |      at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
alfio_1  |      at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
alfio_1  |      at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
alfio_1  |      at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
alfio_1  |      at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
alfio_1  |      at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
alfio_1  |      at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
alfio_1  |      at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
alfio_1  |      at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
alfio_1  |      at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
alfio_1  |      at alfio.manager.NotificationManager.sendWaitingMessages(NotificationManager.java:316) ~[classes/:?]
alfio_1  |      at alfio.manager.NotificationManager$$FastClassBySpringCGLIB$$3482d7f4.invoke(<generated>) ~[classes/:?]
alfio_1  |      at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.5.RELEASE.jar:5.2.5.RELEASE]
alfio_1  |      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
alfio_1  |      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
alfio_1  |      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
alfio_1  |      at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366) [spring-tx-5.2.5.RELEASE.jar:5.2.5.RELEASE]
alfio_1  |      at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) [spring-tx-5.2.5.RELEASE.jar:5.2.5.RELEASE]
alfio_1  |      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
alfio_1  |      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) [spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
alfio_1  |      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) [spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
alfio_1  |      at alfio.manager.NotificationManager$$EnhancerBySpringCGLIB$$76407b7.sendWaitingMessages(<generated>) [classes/:?]
alfio_1  |      at alfio.job.Jobs.sendEmails(Jobs.java:103) [classes/:?]
alfio_1  |      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
alfio_1  |      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
alfio_1  |      at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
alfio_1  |      at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
alfio_1  |      at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
alfio_1  |      at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
alfio_1  |      at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
alfio_1  |      at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:?]
alfio_1  |      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
alfio_1  |      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
alfio_1  |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
alfio_1  |      at java.lang.Thread.run(Unknown Source) [?:?]
```

Alfio Version: latest

Can somebody tell me how to fix the issue? My mailcow server is not broken: When I use thunderbird with port 587 and STARTLS I can send E-Mails.

**Comment by cbellone** [comment]
Hi, it looks like you have some networking issue (or EGRESS firewall rule) preventing you to access your mailserver

```
Operation timed out (Connection timed out)
```

please double check your docker/network configuration

**Comment by cbellone** [comment]
If you don't mind I'd like to move this to a discussion, since it's not likely to be an alf.io bug (might be related to the Java Virtual Machine though...)

Not sure if you have the "telnet" command in the docker image anyway can you try something like this
```
telnet mail.example.org 587
```
because ping uses another protocol and another port, so the firewall (if any) might be blocking port 587 specifically
