### ISSUE TITLE
Unable to upgrade to 2.0-M4-2204 using WAR

### ISSUE THREAD

**Issue by doug86i** [alfio-event/alf.io#1103]
While trying to boot the new Alf.io 2.0-M4-2204 WAR I receive the following errors in the boot log:

(Swapping back to 2.0-M4 war boots properly)

`12:49:45.087 [main] INFO  alfio.config.SpringBootLauncher - The following 2 profiles are active: "spring-boot", "prod"
12:50:02.437 [main] INFO  alfio.config.ConfigurationStatusChecker - performing migration from previous version, if any
12:50:03.116 [main] ERROR alfio.config.ConfigurationStatusChecker - unable to perform data migration. Please report this issue.
org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
	at org.springframework.dao.support.DataAccessUtils.nullableSingleResult(DataAccessUtils.java:97) ~[spring-tx-5.3.18.jar!/:5.3.18]
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:244) ~[spring-jdbc-5.3.18.jar!/:5.3.18]
	at ch.digitalfondue.npjt.QueryType.handleSingleObject(QueryType.java:177) ~[npjt-extra-2.0.4.jar!/:?]
	at ch.digitalfondue.npjt.QueryType.access$700(QueryType.java:51) ~[npjt-extra-2.0.4.jar!/:?]
	at ch.digitalfondue.npjt.QueryType$2.doQuery(QueryType.java:117) ~[npjt-extra-2.0.4.jar!/:?]
	at ch.digitalfondue.npjt.QueryType$2.apply(QueryType.java:87) ~[npjt-extra-2.0.4.jar!/:?]
	at ch.digitalfondue.npjt.QueryFactory.lambda$from$0(QueryFactory.java:191) ~[npjt-extra-2.0.4.jar!/:?]
	at com.sun.proxy.$Proxy83.countExistingTickets(Unknown Source) ~[?:?]
	at alfio.manager.system.DataMigrator.fixAvailableSeats(DataMigrator.java:291) ~[classes!/:?]
	at alfio.manager.system.DataMigrator.lambda$migrateEventToCurrentVersion$10(DataMigrator.java:205) ~[classes!/:?]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.18.jar!/:5.3.18]
	at alfio.manager.system.DataMigrator.migrateEventToCurrentVersion(DataMigrator.java:202) ~[classes!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at alfio.manager.system.DataMigrator.migrateEventsToCurrentVersion(DataMigrator.java:126) ~[classes!/:?]
	at alfio.manager.system.DataMigrator$$FastClassBySpringCGLIB$$afd9fc78.invoke(<generated>) ~[classes!/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.18.jar!/:5.3.18]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.18.jar!/:5.3.18]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.18.jar!/:5.3.18]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.18.jar!/:5.3.18]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.18.jar!/:5.3.18]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.18.jar!/:5.3.18]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.18.jar!/:5.3.18]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.18.jar!/:5.3.18]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.18.jar!/:5.3.18]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-5.3.18.jar!/:5.3.18]
	at alfio.manager.system.DataMigrator$$EnhancerBySpringCGLIB$$a6ed6167.migrateEventsToCurrentVersion(<generated>) ~[classes!/:?]
	at alfio.config.ConfigurationStatusChecker.onApplicationEvent(ConfigurationStatusChecker.java:87) [classes!/:?]
	at alfio.config.ConfigurationStatusChecker.onApplicationEvent(ConfigurationStatusChecker.java:39) [classes!/:?]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) [spring-context-5.3.18.jar!/:5.3.18]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) [spring-context-5.3.18.jar!/:5.3.18]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) [spring-context-5.3.18.jar!/:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) [spring-context-5.3.18.jar!/:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) [spring-context-5.3.18.jar!/:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938) [spring-context-5.3.18.jar!/:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) [spring-context-5.3.18.jar!/:5.3.18]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) [spring-boot-2.5.12.jar!/:2.5.12]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.5.12.jar!/:2.5.12]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:448) [spring-boot-2.5.12.jar!/:2.5.12]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) [spring-boot-2.5.12.jar!/:2.5.12]
	at alfio.config.SpringBootLauncher.main(SpringBootLauncher.java:55) [classes!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [alfio-boot.war:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [alfio-boot.war:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [alfio-boot.war:?]
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) [alfio-boot.war:?]
12:50:03.192 [main] INFO  alfio.config.SpringBootLauncher - Started SpringBootLauncher in 19.681 seconds (JVM running for 23.363)
12:50:03.237 [main] INFO  alfio.config.SpringBootLauncher - profiles: requested , active spring-boot, prod`

Server is running Debian 10

> java -version
> openjdk version "11.0.16" 2022-07-19
> OpenJDK Runtime Environment (build 11.0.16+8-post-Debian-1deb10u1)
> OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Debian-1deb10u1, mixed mode, sharing)

**Comment by syjer** [comment]
most likely culprit:

```java
@Query("select available_seats from events_statistics where id = :eventId")
    Integer countExistingTickets(@Bind("eventId") int eventId);
```

Should be Optional<Integer> . If an event does not exist in the events_statistics viewe it may fail.
