### ISSUE TITLE
Cannot process donation in main branch

### ISSUE THREAD

**Issue by syjer** [alfio-event/alf.io#1324]
Appear to be an issue with the main branch.

Currently adding a donation to an event cause the following issue when trying to complete the first step:

```
java.lang.NullPointerException: element cannot be mapped to a null key
        at java.util.Objects.requireNonNull(Objects.java:235) ~[?:?]
        at java.util.stream.Collectors.lambda$groupingBy$53(Collectors.java:1142) ~[?:?]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at alfio.manager.AdditionalServiceManager.reserveAdditionalServicesForReservation(AdditionalServiceManager.java:451) ~[main/:?]
        at alfio.manager.AdditionalServiceManager.bookAdditionalServicesForReservation(AdditionalServiceManager.java:392) ~[main/:?]
        at alfio.manager.AdditionalServiceManager$$FastClassBySpringCGLIB$$781546cd.invoke(<generated>) ~[main/:?]

```

Step to reproduce:

create an event with payment, add a donation with variable amount, publish event -> try to buy a ticket with a donation more than 0.

**Comment by syjer** [comment]
The main issue is that we are not linking the donation to the "first" ticket, so in the end we get a reservation with:

```json
"additionalServiceWithData":[
      {
         "title":{
            "en":"test"
         },
         "itemId":20,
         "serviceId":6,
         "ticketUUID":null,
         "ticketFieldConfiguration":[
            
         ]
      }
```

then the ticketUUID is used a as a key "null" .
