### ISSUE TITLE
ERROR: cannot change name of view column "tai_additional_info" to "e_version"

### ISSUE THREAD

**Issue by daedric7** [alfio-event/alf.io#1337]
**Describe the bug**
Don't what happened or caused. Noticed alfio having high cpu usage, went to check logs and found the data bellow:

**To Reproduce**
It's happening every restart.

Docker Logs:

```
alfio-db-1  |
alfio-db-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
alfio-db-1  |
alfio-db-1  | 2024-02-25 00:14:28.727 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
alfio-db-1  | 2024-02-25 00:14:28.727 UTC [1] LOG:  listening on IPv6 address "::", port 5432
alfio-db-1  | 2024-02-25 00:14:28.739 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
alfio-db-1  | 2024-02-25 00:14:28.796 UTC [26] LOG:  database system was shut down at 2024-02-25 00:14:02 UTC
alfio-db-1  | 2024-02-25 00:14:28.863 UTC [1] LOG:  database system is ready to accept connections
alfio-1     |     _    _  __  _
alfio-1     |    / \  | |/ _|(_) ___
alfio-1     |   / _ \ | | |_ | |/ _ \
alfio-1     |  / ___ \| |  _|| | (_) |
alfio-1     | /_/   \_\_|_|(_)_|\___/
alfio-1     |
alfio-1     | >> powered by Spring Boot
alfio-1     |
alfio-1     | 2024-02-25 00:14:31.677 [main] INFO  alfio.config.SpringBootLauncher - Starting SpringBootLauncher using Java 15.0.7 on 816e5c415e79 with PID 1 (/home/alfio/app/WEB-INF/classes started by alfio in /home/alfio/app)
alfio-1     | 2024-02-25 00:14:31.735 [main] INFO  alfio.config.SpringBootLauncher - The following 3 profiles are active: "spring-boot", "stdout", "jdbc-session"
alfio-1     | 2024-02-25 00:14:37.297 [main] WARN  alfio.config.DataSourceConfiguration - You're accessing the database using a superuser. This is highly discouraged since it will disable the row security policy checks.
alfio-db-1  | 2024-02-25 00:14:37.939 UTC [33] ERROR:  cannot change name of view column "tai_additional_info" to "e_version"
alfio-db-1  | 2024-02-25 00:14:37.939 UTC [33] STATEMENT:  create or replace view checkin_ticket_event_and_category_info as
alfio-db-1  |   (
alfio-db-1  |       select
alfio-db-1  |           -- ticket
alfio-db-1  |
alfio-db-1  |           t.id                                t_id,
alfio-db-1  |           t.uuid                              t_uuid,
alfio-db-1  |           t.creation                          t_creation,
alfio-db-1  |           t.category_id                       t_category_id,
alfio-db-1  |           t.status                            t_status,
alfio-db-1  |           t.event_id                          t_event_id,
alfio-db-1  |           t.src_price_cts                     t_src_price_cts,
alfio-db-1  |           t.final_price_cts                   t_final_price_cts,
alfio-db-1  |           t.vat_cts                           t_vat_cts,
alfio-db-1  |           t.discount_cts                      t_discount_cts,
alfio-db-1  |           t.tickets_reservation_id            t_tickets_reservation_id,
alfio-db-1  |           t.full_name                         t_full_name,
alfio-db-1  |           t.first_name                        t_first_name,
alfio-db-1  |           t.last_name                         t_last_name,
alfio-db-1  |           t.email_address                     t_email_address,
alfio-db-1  |           t.locked_assignment                 t_locked_assignment,
alfio-db-1  |           t.user_language                     t_user_language,
alfio-db-1  |           t.ext_reference                     t_ext_reference,
alfio-db-1  |           t.currency_code                     t_currency_code,
alfio-db-1  |           t.tags                              t_tags,
alfio-db-1  |           t.subscription_id_fk                t_subscription_id,
alfio-db-1  |           t.vat_status                        t_vat_status,
alfio-db-1  |
alfio-db-1  |           -- ticket reservation
alfio-db-1  |
alfio-db-1  |           tr.id                               tr_id,
alfio-db-1  |           tr.validity                         tr_validity,
alfio-db-1  |           tr.status                           tr_status,
alfio-db-1  |           tr.full_name                        tr_full_name,
alfio-db-1  |           tr.first_name                       tr_first_name,
alfio-db-1  |           tr.last_name                        tr_last_name,
alfio-db-1  |           tr.email_address                    tr_email_address,
alfio-db-1  |           tr.billing_address                  tr_billing_address,
alfio-db-1  |           tr.confirmation_ts                  tr_confirmation_ts,
alfio-db-1  |           tr.latest_reminder_ts               tr_latest_reminder_ts,
alfio-db-1  |           tr.payment_method                   tr_payment_method,
alfio-db-1  |           tr.offline_payment_reminder_sent    tr_offline_payment_reminder_sent,
alfio-db-1  |           tr.promo_code_id_fk                 tr_promo_code_id_fk,
alfio-db-1  |           tr.automatic                        tr_automatic,
alfio-db-1  |           tr.user_language                    tr_user_language,
alfio-db-1  |           tr.direct_assignment                tr_direct_assignment,
alfio-db-1  |           tr.invoice_number                   tr_invoice_number,
alfio-db-1  |           tr.invoice_model                    tr_invoice_model,
alfio-db-1  |           tr.vat_status                       tr_vat_status,
alfio-db-1  |           tr.vat_nr                           tr_vat_nr,
alfio-db-1  |           tr.vat_country                      tr_vat_country,
alfio-db-1  |           tr.invoice_requested                tr_invoice_requested,
alfio-db-1  |           tr.used_vat_percent                 tr_used_vat_percent,
alfio-db-1  |           tr.vat_included                     tr_vat_included,
alfio-db-1  |           tr.creation_ts                      tr_creation_ts,
alfio-db-1  |           tr.customer_reference               tr_customer_reference,
alfio-db-1  |           tr.registration_ts                  tr_registration_ts,
alfio-db-1  |
alfio-db-1  |           tr.billing_address_company          tr_billing_address_company,
alfio-db-1  |           tr.billing_address_line1            tr_billing_address_line1,
alfio-db-1  |           tr.billing_address_line2            tr_billing_address_line2,
alfio-db-1  |           tr.billing_address_city             tr_billing_address_city,
alfio-db-1  |           tr.billing_address_state            tr_billing_address_state,
alfio-db-1  |           tr.billing_address_zip              tr_billing_address_zip,
alfio-db-1  |           tr.invoicing_additional_information tr_invoicing_additional_information,
alfio-db-1  |
alfio-db-1  |           tr.src_price_cts                    tr_src_price_cts,
alfio-db-1  |           tr.final_price_cts                  tr_final_price_cts,
alfio-db-1  |           tr.vat_cts                          tr_vat_cts,
alfio-db-1  |           tr.discount_cts                     tr_discount_cts,
alfio-db-1  |           tr.currency_code                    tr_currency_code,
alfio-db-1  |
alfio-db-1  |           -- ticket category
alfio-db-1  |           tc.id                               tc_id,
alfio-db-1  |           tc.inception                        tc_inception,
alfio-db-1  |           tc.expiration                       tc_expiration,
alfio-db-1  |           tc.max_tickets                      tc_max_tickets,
alfio-db-1  |           tc.name                             tc_name,
alfio-db-1  |           tc.src_price_cts                    tc_src_price_cts,
alfio-db-1  |           tc.access_restricted                tc_access_restricted,
alfio-db-1  |           tc.tc_status                        tc_tc_status,
alfio-db-1  |           tc.event_id                         tc_event_id,
alfio-db-1  |           tc.bounded                          tc_bounded,
alfio-db-1  |           tc.category_code                    tc_category_code,
alfio-db-1  |           tc.valid_checkin_from               tc_valid_checkin_from,
alfio-db-1  |           tc.valid_checkin_to                 tc_valid_checkin_to,
alfio-db-1  |           tc.ticket_validity_start            tc_ticket_validity_start,
alfio-db-1  |           tc.ticket_validity_end              tc_ticket_validity_end,
alfio-db-1  |           tc.ordinal                          tc_ordinal,
alfio-db-1  |           tc.ticket_checkin_strategy          tc_ticket_checkin_strategy,
alfio-db-1  |           tc.metadata                         tc_metadata,
alfio-db-1  |           tc.ticket_access_type               tc_ticket_access_type,
alfio-db-1  |
alfio-db-1  |           -- event
alfio-db-1  |
alfio-db-1  |           e.id                                e_id,
alfio-db-1  |           e.format                            e_format,
alfio-db-1  |           e.short_name                        e_short_name,
alfio-db-1  |           e.display_name                      e_display_name,
alfio-db-1  |           e.start_ts                          e_start_ts,
alfio-db-1  |           e.end_ts                            e_end_ts,
alfio-db-1  |           e.time_zone                         e_time_zone,
alfio-db-1  |           e.private_key                       e_private_key,
alfio-db-1  |           e.metadata                          e_metadata,
alfio-db-1  |           e.org_id                            e_org_id,
alfio-db-1  |           e.locales                           e_locales,
alfio-db-1  |           e.version                           e_version,
alfio-db-1  |           (select jsonb_object_agg(tfc.field_name, retrieve_field_value_as_json(tfc.field_type, tfv.field_value)) as additional_info
alfio-db-1  |               from purchase_context_field_value tfv
alfio-db-1  |                   inner join purchase_context_field_configuration tfc on tfv.field_configuration_id_fk = tfc.id
alfio-db-1  |               where event_id_fk = e.id and tfv.ticket_id_fk = t.id)       tai_additional_info,
alfio-db-1  |           case when t.status = 'ACQUIRED' or t.status = 'TO_BE_PAID' then 0 else 2 end as t_status_priority
alfio-db-1  |
alfio-db-1  |       from ticket t
alfio-db-1  |                inner join tickets_reservation tr on t.tickets_reservation_id = tr.id
alfio-db-1  |                inner join ticket_category tc on t.category_id = tc.id
alfio-db-1  |                inner join event e on e.id = t.event_id
alfio-db-1  |       where t.status in ('ACQUIRED', 'CHECKED_IN', 'TO_BE_PAID')
alfio-db-1  |         and t.first_name is not null
alfio-db-1  |         and (t.first_name <> '') IS TRUE
alfio-db-1  |         and t.last_name is not null
alfio-db-1  |         and (t.last_name <> '') IS TRUE
alfio-db-1  |         and t.email_address is not null
alfio-db-1  |         and (t.email_address <> '') IS TRUE
alfio-db-1  |   )
alfio-1     | 2024-02-25 00:14:37.982 [main] WARN  org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty web server
alfio-1     | 2024-02-25 00:14:38.083 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
alfio-1     | org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty web server
alfio-1     |   at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:163) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577) ~[spring-context-5.3.18.jar:5.3.18]
alfio-1     |   at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:448) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at alfio.config.SpringBootLauncher.main(SpringBootLauncher.java:55) ~[classes/:?]
alfio-1     | Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty web server
alfio-1     |   at org.springframework.boot.web.embedded.jetty.JettyWebServer.initialize(JettyWebServer.java:129) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.web.embedded.jetty.JettyWebServer.<init>(JettyWebServer.java:90) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getJettyWebServer(JettyServletWebServerFactory.java:429) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getWebServer(JettyServletWebServerFactory.java:170) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:182) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   ... 6 more
alfio-1     | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'springSessionRepositoryFilter' defined in org.springframework.session.jdbc.config.annotation.web.http.JdbcHttpSessionConfiguration: Unsatisfied dependency expressed through method 'springSessionRepositoryFilter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'migrator' defined in alfio.config.DataSourceConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'migrator' threw exception; nested exception is org.flywaydb.core.api.FlywayException: Error while executing afterMigrate callback:
alfio-1     | Migration afterMigrate__009_VIEW_checkin_ticket_event_and_category_info.sql failed
alfio-1     | ----------------------------------------------------------------------------------
alfio-1     | SQL State  : 42P16
alfio-1     | Error Code : 0
alfio-1     | Message    : ERROR: cannot change name of view column "tai_additional_info" to "e_version"
alfio-1     | Location   : alfio/db/PGSQL/afterMigrate__009_VIEW_checkin_ticket_event_and_category_info.sql (/home/alfio/app/WEB-INF/classes/alfio/db/PGSQL/afterMigrate__009_VIEW_checkin_ticket_event_and_category_info.sql)
alfio-1     | Line       : 36
alfio-1     | Statement  : create or replace view checkin_ticket_event_and_category_info as
alfio-1     | (
alfio-1     |     select
alfio-1     |         -- ticket
alfio-1     |
alfio-1     |         t.id                                t_id,
alfio-1     |         t.uuid                              t_uuid,
alfio-1     |         t.creation                          t_creation,
alfio-1     |         t.category_id                       t_category_id,
alfio-1     |         t.status                            t_status,
alfio-1     |         t.event_id                          t_event_id,
alfio-1     |         t.src_price_cts                     t_src_price_cts,
alfio-1     |         t.final_price_cts                   t_final_price_cts,
alfio-1     |         t.vat_cts                           t_vat_cts,
alfio-1     |         t.discount_cts                      t_discount_cts,
alfio-1     |         t.tickets_reservation_id            t_tickets_reservation_id,
alfio-1     |         t.full_name                         t_full_name,
alfio-1     |         t.first_name                        t_first_name,
alfio-1     |         t.last_name                         t_last_name,
alfio-1     |         t.email_address                     t_email_address,
alfio-1     |         t.locked_assignment                 t_locked_assignment,
alfio-1     |         t.user_language                     t_user_language,
alfio-1     |         t.ext_reference                     t_ext_reference,
alfio-1     |         t.currency_code                     t_currency_code,
alfio-1     |         t.tags                              t_tags,
alfio-1     |         t.subscription_id_fk                t_subscription_id,
alfio-1     |         t.vat_status                        t_vat_status,
alfio-1     |
alfio-1     |         -- ticket reservation
alfio-1     |
alfio-1     |         tr.id                               tr_id,
alfio-1     |         tr.validity                         tr_validity,
alfio-1     |         tr.status                           tr_status,
alfio-1     |         tr.full_name                        tr_full_name,
alfio-1     |         tr.first_name                       tr_first_name,
alfio-1     |         tr.last_name                        tr_last_name,
alfio-1     |         tr.email_address                    tr_email_address,
alfio-1     |         tr.billing_address                  tr_billing_address,
alfio-1     |         tr.confirmation_ts                  tr_confirmation_ts,
alfio-1     |         tr.latest_reminder_ts               tr_latest_reminder_ts,
alfio-1     |         tr.payment_method                   tr_payment_method,
alfio-1     |         tr.offline_payment_reminder_sent    tr_offline_payment_reminder_sent,
alfio-1     |         tr.promo_code_id_fk                 tr_promo_code_id_fk,
alfio-1     |         tr.automatic                        tr_automatic,
alfio-1     |         tr.user_language                    tr_user_language,
alfio-1     |         tr.direct_assignment                tr_direct_assignment,
alfio-1     |         tr.invoice_number                   tr_invoice_number,
alfio-1     |         tr.invoice_model                    tr_invoice_model,
alfio-1     |         tr.vat_status                       tr_vat_status,
alfio-1     |         tr.vat_nr                           tr_vat_nr,
alfio-1     |         tr.vat_country                      tr_vat_country,
alfio-1     |         tr.invoice_requested                tr_invoice_requested,
alfio-1     |         tr.used_vat_percent                 tr_used_vat_percent,
alfio-1     |         tr.vat_included                     tr_vat_included,
alfio-1     |         tr.creation_ts                      tr_creation_ts,
alfio-1     |         tr.customer_reference               tr_customer_reference,
alfio-1     |         tr.registration_ts                  tr_registration_ts,
alfio-1     |
alfio-1     |         tr.billing_address_company          tr_billing_address_company,
alfio-1     |         tr.billing_address_line1            tr_billing_address_line1,
alfio-1     |         tr.billing_address_line2            tr_billing_address_line2,
alfio-1     |         tr.billing_address_city             tr_billing_address_city,
alfio-1     |         tr.billing_address_state            tr_billing_address_state,
alfio-1     |         tr.billing_address_zip              tr_billing_address_zip,
alfio-1     |         tr.invoicing_additional_information tr_invoicing_additional_information,
alfio-1     |
alfio-1     |         tr.src_price_cts                    tr_src_price_cts,
alfio-1     |         tr.final_price_cts                  tr_final_price_cts,
alfio-1     |         tr.vat_cts                          tr_vat_cts,
alfio-1     |         tr.discount_cts                     tr_discount_cts,
alfio-1     |         tr.currency_code                    tr_currency_code,
alfio-1     |
alfio-1     |         -- ticket category
alfio-1     |         tc.id                               tc_id,
alfio-1     |         tc.inception                        tc_inception,
alfio-1     |         tc.expiration                       tc_expiration,
alfio-1     |         tc.max_tickets                      tc_max_tickets,
alfio-1     |         tc.name                             tc_name,
alfio-1     |         tc.src_price_cts                    tc_src_price_cts,
alfio-1     |         tc.access_restricted                tc_access_restricted,
alfio-1     |         tc.tc_status                        tc_tc_status,
alfio-1     |         tc.event_id                         tc_event_id,
alfio-1     |         tc.bounded                          tc_bounded,
alfio-1     |         tc.category_code                    tc_category_code,
alfio-1     |         tc.valid_checkin_from               tc_valid_checkin_from,
alfio-1     |         tc.valid_checkin_to                 tc_valid_checkin_to,
alfio-1     |         tc.ticket_validity_start            tc_ticket_validity_start,
alfio-1     |         tc.ticket_validity_end              tc_ticket_validity_end,
alfio-1     |         tc.ordinal                          tc_ordinal,
alfio-1     |         tc.ticket_checkin_strategy          tc_ticket_checkin_strategy,
alfio-1     |         tc.metadata                         tc_metadata,
alfio-1     |         tc.ticket_access_type               tc_ticket_access_type,
alfio-1     |
alfio-1     |         -- event
alfio-1     |
alfio-1     |         e.id                                e_id,
alfio-1     |         e.format                            e_format,
alfio-1     |         e.short_name                        e_short_name,
alfio-1     |         e.display_name                      e_display_name,
alfio-1     |         e.start_ts                          e_start_ts,
alfio-1     |         e.end_ts                            e_end_ts,
alfio-1     |         e.time_zone                         e_time_zone,
alfio-1     |         e.private_key                       e_private_key,
alfio-1     |         e.metadata                          e_metadata,
alfio-1     |         e.org_id                            e_org_id,
alfio-1     |         e.locales                           e_locales,
alfio-1     |         e.version                           e_version,
alfio-1     |         (select jsonb_object_agg(tfc.field_name, retrieve_field_value_as_json(tfc.field_type, tfv.field_value)) as additional_info
alfio-1     |             from purchase_context_field_value tfv
alfio-1     |                 inner join purchase_context_field_configuration tfc on tfv.field_configuration_id_fk = tfc.id
alfio-1     |             where event_id_fk = e.id and tfv.ticket_id_fk = t.id)       tai_additional_info,
alfio-1     |         case when t.status = 'ACQUIRED' or t.status = 'TO_BE_PAID' then 0 else 2 end as t_status_priority
alfio-1     |
alfio-1     |     from ticket t
alfio-1     |              inner join tickets_reservation tr on t.tickets_reservation_id = tr.id
alfio-1     |              inner join ticket_category tc on t.category_id = tc.id
alfio-1     |              inner join event e on e.id = t.event_id
alfio-1     |     where t.status in ('ACQUIRED', 'CHECKED_IN', 'TO_BE_PAID')
alfio-1     |       and t.first_name is not null
alfio-1     |       and (t.first_name <> '') IS TRUE
alfio-1     |       and t.last_name is not null
alfio-1     |       and (t.last_name <> '') IS TRUE
alfio-1     |       and t.email_address is not null
alfio-1     |       and (t.email_address <> '') IS TRUE
alfio-1     | )
alfio-1     |
alfio-1     |   at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.18.jar:5.3.18]
alfio-1     |   at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541) ~[spring-beans-5.3.18.jar:5.3.18]
alfio-1     |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.18.jar:5.3.18]
alfio-1     |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.18.jar:5.3.18]
alfio-1     |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.18.jar:5.3.18]
alfio-1     |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.18.jar:5.3.18]
alfio-1     |   at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.18.jar:5.3.18]
alfio-1     |   at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.18.jar:5.3.18]
alfio-1     |   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.18.jar:5.3.18]
alfio-1     |   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) ~[spring-beans-5.3.18.jar:5.3.18]
alfio-1     |   at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:212) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addAsRegistrationBean(ServletContextInitializerBeans.java:175) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addAsRegistrationBean(ServletContextInitializerBeans.java:170) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addAdaptableBeans(ServletContextInitializerBeans.java:155) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:87) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getServletContextInitializerBeans(ServletWebServerApplicationContext.java:260) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:234) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.web.embedded.jetty.ServletContextInitializerConfiguration.callInitializers(ServletContextInitializerConfiguration.java:65) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.web.embedded.jetty.ServletContextInitializerConfiguration.configure(ServletContextInitializerConfiguration.java:54) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:498) ~[jetty-webapp-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409) ~[jetty-webapp-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288) ~[jetty-servlet-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524) ~[jetty-webapp-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:426) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:253) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.server.Server.start(Server.java:423) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.server.Server.doStart(Server.java:387) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
alfio-1     |   at org.springframework.boot.web.embedded.jetty.JettyWebServer.initialize(JettyWebServer.java:123) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.web.embedded.jetty.JettyWebServer.<init>(JettyWebServer.java:90) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getJettyWebServer(JettyServletWebServerFactory.java:429) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getWebServer(JettyServletWebServerFactory.java:170) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:182) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160) ~[spring-boot-2.5.12.jar:2.5.12]
alfio-1     |   ... 6 more
alfio-1     | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'migrator' defined in alfio.config.DataSourceConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'migrator' threw exception; nested exception is org.flywaydb.core.api.FlywayException: Error while executing afterMigrate callback:
alfio-1     | Migration afterMigrate__009_VIEW_checkin_ticket_event_and_category_info.sql failed
alfio-1     | ----------------------------------------------------------------------------------
alfio-1     | SQL State  : 42P16
alfio-1     | Error Code : 0

```

**Comment by daedric7** [comment]
Update: deleting the view from the DB allowed Alfio to start without errors. The View has been created.

I'll request for tests to be executed.
