### ISSUE TITLE
Mollie doesn't appear in payment methods

### ISSUE THREAD

**Issue by Tiddons** [alfio-event/alf.io#1381]
**Describe the bug**
Our organisation just set up alf.io on our cloud server using docker.
Everything seems to work fine but I can't manage to get mollie to show up as a payment method. 
In the organisation settings there is a mollie login button and that one doesn't seem to work either.
Can that explain why mollie won't show as a payment option? (everything else displays)

**Server:**
 - OS: Ubuntu 20.04
 - Docker

Thanks in advance

**Comment by mrIllo** [comment]
How could you solve this?

**Comment by mrIllo** [comment]
After much debugging: looking into logging it shows why: 

2025-04-11T21:34:23.070+02:00  WARN 1 --- [Alf.io] [qtp366180667-54] a.m.p.MollieWebhookPaymentManager        : Unsupported payment methods found: **[banktransfer, eps]**. Please check configuration
2025-04-11T21:34:23.078+02:00  WARN 1 --- [Alf.io] [qtp366180667-54] a.m.p.MollieWebhookPaymentManager        : cannot fetch payment methods

java.lang.IllegalStateException: unsupported methods found
        at alfio.manager.payment.MollieWebhookPaymentManager.fetchAvailablePaymentMethods(MollieWebhookPaymentManager.java:237) ~[alfio-boot.jar:2.0-M5-2502]
        at alfio.manager.payment.MollieWebhookPaymentManager.lambda$retrieveAvailablePaymentMethods$1(MollieWebhookPaymentManager.java:182) ~[alfio-boot.jar:2.0-M5-2502]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2688) ~[caffeine-3.1.8.jar:3.1.8]
        at java.base/java.util.concurrent.ConcurrentHashMap.compute(Unknown Source) ~[?:?]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2686) ~[caffeine-3.1.8.jar:3.1.8]
......................

so it comes down that your Mollie Account is checked for your accepted methods and if unsupported are found, Mollie gets silently removed as payment option. Solution is to create/use profiles in your Mollie account to have different settings and for alf.io only use what is supported here.
