### ISSUE TITLE
java.security.InvalidKeyException

### ISSUE THREAD

**Issue by cougil** [alfio-event/alf.io#380]
Hi!

We are starting to test Alf.io just to see how it works and if we can use it for our [Java & JVM conference in Barcelona](http://www.jbcnconf.com) and we found an issue trying to build the Docker image. After running `./gradlew distribution` we get the following exception:

```
alfio.controller.ReservationFlowIntegrationTest > reservationFlowTest FAILED
    java.lang.IllegalStateException: java.security.InvalidKeyException: Illegal key size or default parameters
        at alfio.manager.CheckInManager.encrypt(CheckInManager.java:256)
        at alfio.manager.CheckInManager.lambda$null$15(CheckInManager.java:338)
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at alfio.manager.CheckInManager.lambda$getEncryptedAttendeesInformation$16(CheckInManager.java:342)
        at java.util.Optional.map(Optional.java:215)
        at alfio.manager.CheckInManager.getEncryptedAttendeesInformation(CheckInManager.java:308)
        at alfio.manager.CheckInManager$$FastClassBySpringCGLIB$$3941cbae.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
        at alfio.manager.CheckInManager$$EnhancerBySpringCGLIB$$3a81c0a3.getEncryptedAttendeesInformation(<generated>)
        at alfio.controller.api.admin.CheckInApiController.lambda$getOfflineEncryptedInfo$9(CheckInApiController.java:189)
        at java.util.Optional.map(Optional.java:215)
        at alfio.controller.api.admin.CheckInApiController.getOfflineEncryptedInfo(CheckInApiController.java:173)
        at alfio.controller.ReservationFlowIntegrationTest.reservationFlowTest(ReservationFlowIntegrationTest.java:417)

        Caused by:
        java.security.InvalidKeyException: Illegal key size or default parameters
            at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)
            at javax.crypto.Cipher.implInit(Cipher.java:801)
            at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
            at javax.crypto.Cipher.init(Cipher.java:1249)
            at javax.crypto.Cipher.init(Cipher.java:1186)
            at alfio.manager.CheckInManager.encrypt(CheckInManager.java:251)
            ... 26 more

260 tests completed, 1 failed
```

How we can solve it? We are using Java 1.8 from Oracle (1.8.0_141)

Best,

**Comment by cbellone** [comment]
Hi @cougil!
Thank you for using alf.io!

Alf.io make use of strong encryption algorithms in that particular method (CheckInManager.java:256)
could you please check if you have the JCE Unlimited Strength installed?
http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

Usually this is not a problem, as most of the linux distributions already contain the JCE (especially if you use OpenJDK builds), but it looks like you don't have it...

**Comment by cougil** [comment]
Hi Celestino!
I was expecting something like this (it reminded me the typical error that is related with the absence of the Java Cryptographic Extension)
Thank you, it was exactly this problem!
Btw, I'd recommend you just to include as a requirement on the README just to let everybody know that is a must for building Alf.io ;-)
Best,

**Comment by cbellone** [comment]
yes, will do. Thanks for pointing it out :-)
