### ISSUE TITLE
Stripe test mode is not working

### ISSUE THREAD

**Issue by baccinelli** [alfio-event/alf.io#899]
**Describe the bug**
When configuring a test api_key and secret the payment fails

**To Reproduce**
1. Configure stripe payment (with a test api key)
2. Create an avent with fee
3. From public front end try to buy the ticket with credit card (stripe)
4. Insert the test card number (4242 4242 4242 4242)
5. An error will be raised  
![image](https://user-images.githubusercontent.com/59366136/81570240-9d388980-93a0-11ea-82d3-e255e59467fb.png)

**Expected behavior**
Transaction sould be completed (test mode)

**Screenshots**
This is the warning message on credit card popup  
![image](https://user-images.githubusercontent.com/59366136/81570603-1a63fe80-93a1-11ea-9163-9084d8f69fc9.png)

**Desktop (please complete the following information):**
 - OS: any
 - Browser : any
 - Version : any

**Additional context**
*Stack strace info:*  
17:51:24.187 [qtp592207425-22] ERROR alfio.manager.TicketReservationManager - unexpected error during payment confirmation
org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0  
        at org.springframework.dao.support.DataAccessUtils.nullableSingleResult(DataAccessUtils.java:97) ~[spring-tx-5.2.5.RELEASE.jar:5.2.5.RELEASE]  
        at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:237) ~[spring-jdbc-5.2.5.RELE
ASE.jar:5.2.5.RELEASE]  
        at ch.digitalfondue.npjt.QueryType.handleSingleObject(QueryType.java:177) ~[npjt-extra-2.0.3.jar:?]
        at ch.digitalfondue.npjt.QueryType.access$700(QueryType.java:51) ~[npjt-extra-2.0.3.jar:?]
        at ch.digitalfondue.npjt.QueryType$2.doQuery(QueryType.java:117) ~[npjt-extra-2.0.3.jar:?]
        at ch.digitalfondue.npjt.QueryType$2.apply(QueryType.java:87) ~[npjt-extra-2.0.3.jar:?]

**Comment by baccinelli** [comment]
Today it works againg.. maybe a temporary down time?

**Comment by cbellone** [comment]
maybe... they had some high error rates last week
But thanks for opening the issue anyway. 
I would suggest to keep it open, because we have to switch to the new Checkout API as soon as possible
