### ISSUE TITLE
MailjetMailer - error when sending mail on ticket closure

### ISSUE THREAD

**Issue by ehamwey** [alfio-event/alf.io#995]
**Describe the bug**
Upon closing or releasing of any tickets, regardless of "notify the user" checkbox state, there is an error and the system does not respond for 60 seconds, using mailjet as the notifier. 

**To Reproduce**
- Configure alfio per documentation steps on heroku
- Enable mailjet mailer
- Create event, make a ticket reservation, and cancel that reservation via the backend or from the end user perspective

**Expected behavior**
The ticket cancels

**Stack trace:**
`2021-04-09T15:44:01.878017+00:00 app[web.1]: 15:44:01.872 [scheduling-1] WARN  alfio.manager.system.MailjetMailer - error while sending email
2021-04-09T15:44:01.878026+00:00 app[web.1]: java.io.IOException: /172.19.80.134:57124: GOAWAY received
2021-04-09T15:44:01.878026+00:00 app[web.1]: at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:565) ~[java.net.http:?]
2021-04-09T15:44:01.878027+00:00 app[web.1]: at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119) ~[java.net.http:?]
2021-04-09T15:44:01.878027+00:00 app[web.1]: at alfio.manager.system.MailjetMailer.send(MailjetMailer.java:89) ~[classes!/:?]
2021-04-09T15:44:01.878027+00:00 app[web.1]: at alfio.manager.system.DefaultMailer.send(DefaultMailer.java:60) ~[classes!/:?]
2021-04-09T15:44:01.878028+00:00 app[web.1]: at alfio.manager.NotificationManager.sendMessage(NotificationManager.java:349) ~[classes!/:?]
2021-04-09T15:44:01.878028+00:00 app[web.1]: at alfio.manager.NotificationManager.lambda$processMessage$19(NotificationManager.java:334) ~[classes!/:?]
2021-04-09T15:44:01.878029+00:00 app[web.1]: at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
2021-04-09T15:44:01.878030+00:00 app[web.1]: at alfio.manager.NotificationManager.processMessage(NotificationManager.java:333) ~[classes!/:?]
2021-04-09T15:44:01.878030+00:00 app[web.1]: at alfio.manager.NotificationManager.lambda$sendWaitingMessages$16(NotificationManager.java:316) ~[classes!/:?]
2021-04-09T15:44:01.878031+00:00 app[web.1]: at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
2021-04-09T15:44:01.878032+00:00 app[web.1]: at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175) ~[?:?]
2021-04-09T15:44:01.878033+00:00 app[web.1]: at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
2021-04-09T15:44:01.878033+00:00 app[web.1]: at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
2021-04-09T15:44:01.878033+00:00 app[web.1]: at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274) ~[?:?]
2021-04-09T15:44:01.878034+00:00 app[web.1]: at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
2021-04-09T15:44:01.878034+00:00 app[web.1]: at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
2021-04-09T15:44:01.878034+00:00 app[web.1]: at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
2021-04-09T15:44:01.878035+00:00 app[web.1]: at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
2021-04-09T15:44:01.878035+00:00 app[web.1]: at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
2021-04-09T15:44:01.878036+00:00 app[web.1]: at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
2021-04-09T15:44:01.878036+00:00 app[web.1]: at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
2021-04-09T15:44:01.878036+00:00 app[web.1]: at alfio.manager.NotificationManager.sendWaitingMessages(NotificationManager.java:316) ~[classes!/:?]
2021-04-09T15:44:01.878037+00:00 app[web.1]: at alfio.manager.NotificationManager$$FastClassBySpringCGLIB$$3482d7f4.invoke(<generated>) ~[classes!/:?]
2021-04-09T15:44:01.878037+00:00 app[web.1]: at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
2021-04-09T15:44:01.878038+00:00 app[web.1]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
2021-04-09T15:44:01.878038+00:00 app[web.1]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
2021-04-09T15:44:01.878039+00:00 app[web.1]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
2021-04-09T15:44:01.878040+00:00 app[web.1]: at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366) [spring-tx-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
2021-04-09T15:44:01.878040+00:00 app[web.1]: at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) [spring-tx-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
2021-04-09T15:44:01.878041+00:00 app[web.1]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
2021-04-09T15:44:01.878041+00:00 app[web.1]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) [spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
2021-04-09T15:44:01.878042+00:00 app[web.1]: at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) [spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
2021-04-09T15:44:01.878042+00:00 app[web.1]: at alfio.manager.NotificationManager$$EnhancerBySpringCGLIB$$ba4cb4dc.sendWaitingMessages(<generated>) [classes!/:?]
2021-04-09T15:44:01.878043+00:00 app[web.1]: at alfio.job.Jobs.sendEmails(Jobs.java:103) [classes!/:?]
2021-04-09T15:44:01.878043+00:00 app[web.1]: at jdk.internal.reflect.GeneratedMethodAccessor125.invoke(Unknown Source) ~[?:?]
2021-04-09T15:44:01.878044+00:00 app[web.1]: at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2021-04-09T15:44:01.878050+00:00 app[web.1]: at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2021-04-09T15:44:01.878051+00:00 app[web.1]: at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
2021-04-09T15:44:01.878051+00:00 app[web.1]: at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
2021-04-09T15:44:01.878052+00:00 app[web.1]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
2021-04-09T15:44:01.878052+00:00 app[web.1]: at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
2021-04-09T15:44:01.878053+00:00 app[web.1]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
2021-04-09T15:44:01.878053+00:00 app[web.1]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
2021-04-09T15:44:01.878053+00:00 app[web.1]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
2021-04-09T15:44:01.878054+00:00 app[web.1]: at java.lang.Thread.run(Thread.java:834) [?:?]
2021-04-09T15:44:01.878054+00:00 app[web.1]: Caused by: java.io.IOException: /172.19.80.134:57124: GOAWAY received
2021-04-09T15:44:01.878054+00:00 app[web.1]: at jdk.internal.net.http.Http2Connection.handleGoAway(Http2Connection.java:985) ~[java.net.http:?]
2021-04-09T15:44:01.878055+00:00 app[web.1]: at jdk.internal.net.http.Http2Connection.handleConnectionFrame(Http2Connection.java:853) ~[java.net.http:?]
2021-04-09T15:44:01.878055+00:00 app[web.1]: at jdk.internal.net.http.Http2Connection.processFrame(Http2Connection.java:724) ~[java.net.http:?]
2021-04-09T15:44:01.878056+00:00 app[web.1]: at jdk.internal.net.http.frame.FramesDecoder.decode(FramesDecoder.java:155) ~[java.net.http:?]
2021-04-09T15:44:01.878056+00:00 app[web.1]: at jdk.internal.net.http.Http2Connection$FramesController.processReceivedData(Http2Connection.java:232) ~[java.net.http:?]
2021-04-09T15:44:01.878057+00:00 app[web.1]: at jdk.internal.net.http.Http2Connection.asyncReceive(Http2Connection.java:649) ~[java.net.http:?]
2021-04-09T15:44:01.878057+00:00 app[web.1]: at jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.processQueue(Http2Connection.java:1275) ~[java.net.http:?]
2021-04-09T15:44:01.878058+00:00 app[web.1]: at jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175) ~[java.net.http:?]
2021-04-09T15:44:01.878058+00:00 app[web.1]: at jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147) ~[java.net.http:?]
2021-04-09T15:44:01.878059+00:00 app[web.1]: at jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198) ~[java.net.http:?]
2021-04-09T15:44:01.878059+00:00 app[web.1]: at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271) ~[java.net.http:?]
2021-04-09T15:44:01.878059+00:00 app[web.1]: at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224) ~[java.net.http:?]
2021-04-09T15:44:01.878060+00:00 app[web.1]: at jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.runOrSchedule(Http2Connection.java:1293) ~[java.net.http:?]
2021-04-09T15:44:01.878060+00:00 app[web.1]: at jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.onNext(Http2Connection.java:1319) ~[java.net.http:?]
2021-04-09T15:44:01.878061+00:00 app[web.1]: at jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.onNext(Http2Connection.java:1253) ~[java.net.http:?]
2021-04-09T15:44:01.878061+00:00 app[web.1]: at jdk.internal.net.http.common.SSLTube$DelegateWrapper.onNext(SSLTube.java:202) ~[java.net.http:?]
2021-04-09T15:44:01.878061+00:00 app[web.1]: at jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:484) ~[java.net.http:?]
2021-04-09T15:44:01.878062+00:00 app[web.1]: at jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:287) ~[java.net.http:?]
2021-04-09T15:44:01.878062+00:00 app[web.1]: at jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run1(SubscriberWrapper.java:318) ~[java.net.http:?]
2021-04-09T15:44:01.878062+00:00 app[web.1]: at jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run(SubscriberWrapper.java:261) ~[java.net.http:?]
2021-04-09T15:44:01.878063+00:00 app[web.1]: at jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175) ~[java.net.http:?]
2021-04-09T15:44:01.878064+00:00 app[web.1]: at jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147) ~[java.net.http:?]
2021-04-09T15:44:01.878064+00:00 app[web.1]: at jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198) ~[java.net.http:?]
2021-04-09T15:44:01.878064+00:00 app[web.1]: at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271) ~[java.net.http:?]
2021-04-09T15:44:01.878065+00:00 app[web.1]: at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224) ~[java.net.http:?]
2021-04-09T15:44:01.878065+00:00 app[web.1]: at jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:234) ~[java.net.http:?]
2021-04-09T15:44:01.878066+00:00 app[web.1]: at jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:200) ~[java.net.http:?]
2021-04-09T15:44:01.878070+00:00 app[web.1]: at jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:403) ~[java.net.http:?]
2021-04-09T15:44:01.878071+00:00 app[web.1]: at jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:264) ~[java.net.http:?]
2021-04-09T15:44:01.878071+00:00 app[web.1]: at jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175) ~[java.net.http:?]
2021-04-09T15:44:01.878072+00:00 app[web.1]: at jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147) ~[java.net.http:?]
2021-04-09T15:44:01.878072+00:00 app[web.1]: at jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198) ~[java.net.http:?]
2021-04-09T15:44:01.878073+00:00 app[web.1]: ... 3 more
`

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome arm64
 - Version 89.0.4389

**Additional context**
Running on a heroku free instance configured per the guide in the documentation.

**Comment by cbellone** [comment]
Hi @ehamwey ,

thank you very much for reporting this.

What do you mean exactly by:

> the system does not respond for 60 seconds

are you actually unable to use the backoffice or the public facing reservation process (i.e. buy another ticket)?
If so, can you share more details about that?

Regarding the GOAWAY you see in the logs, it will disappear with the next release, which should be available by the end of this month. If you want I can share a SNAPSHOT artifact that you can try and see if it solves the issue.

thanks

**Comment by ehamwey** [comment]
It seems to cause the whole web UI to not respond - i.e. any page loading requests just spin away into eternity (both in the backoffice and the public facing side).

**Comment by cbellone** [comment]
OK.

This is weird, because we have many users using Mailjet with alf.io (including our own customers) so my guess is that the problem could be elsewhere. 

can you please attach the entire log? (a GitHub gist would be perfect)
Please make sure to remove all sensitive information before sharing it

Thanks

**Comment by ehamwey** [comment]
It seems like the problem has resolved itself? I would speculate it is related to just having setup Mailjet, possibly were were configuration/verification steps that were not completed?

**Comment by ehamwey** [comment]
After further investigation it seems like the issue could also have been related to heroku limitations or dyno sleeping. Scaling from the free to hobby plans seems to have mitigated the problem for now?
